Kgaut chandima file edits a3
naccdata/uniform-data-set pull request #187
Opened 2024-08-09 23:34 UTC by kgauthreaux

2024-08-27 01:52 UTC, hewanadun requested changes
@kgauthreaux 

- Mom, dad, siblings, kids YOB validations do not seem to be compatible with participant YOB min/max validations given in A1. Please check.
- There are some issues in missingness and conformity checks for siblings and kids (inconsistencies in allowed values).  I added comments on the first few variables, similar issues are there in all SIB and KID variables and need to be fixed. Please check.
- comp_vars column not filled for the checks involving multiple variables in both files

2024-08-27 01:52 UTC, hewanadun commented on forms/uds/a3/form_a3_ivp_error_checks_mc.csv
> +a3-ivp-c-409,409,Error,a3,I,KID1YOB,Conformity,KID1YOB conforms,"KIDYOB must be a year between 1875 and the current year, or =9999 (unknown)","Q3a1. KID1YOB (Child 1 birth year) must be a year betwee
Double checking whether 1875 is the correct minimum value here, since minimum participant YOB is 1850?

2024-09-28 19:17 UTC, hewanadun commented
@kgauthreaux 
Some issues mentioned above are not fixed yet,

In questions_and_vars file.

- For the variables with double or triple digit codes starting with 0 (such as 00, 01, ... or 000, 001, ...) data type needs to be changed to "string" (currently defined as integer) 
- Please rename the file to "form_a3_ivp_questions_and_vars.csv" (last _ missing in file name so it was uploaded as a new file instead of replacing the existing one with the correct name)

In error checks
- comp_vars column not filled for the checks involving multiple variables in both m/c and plausibility checks files
- All SIB vars that check **<77** (e.g.  checks like "if SIBS is (>0 and <77) then SIB1YOB must be present"), these checks should be changed to **if SIBS (>0 and <=20)**, checking for < 77 is not correct since max allowed is 20
- There are still some KID vars checks that have 888 and 999 (e.g. if KIDS is (<1, 888 (na) or 999 (unknown) then KID1YOB must be blank)
- In KID vars checks there are typos in full_desc, use sibling instead of child - e.g. Q3e3. KID5ETPR (**Sibling** 5 primary dx))
- In KIDXXDAGE vars short_desc, space missing before "then" - e.g. if KIDS is <**1then** KID1DAGE must be blank

2024-10-03 00:21 UTC, kgauthreaux commented
@hewanadun Okay sorry about those lingering errors! I missed that first summary comment last time. I uploaded the forms. Note that 77 is an allowed value for SIBS. It was in the UDSv3 DED but not on the form for some reason. We discussed adding it to the PDF, and I believe we did add it to the REDCap form already (but will do so if not)

2024-10-03 14:45 UTC, hewanadun commented
@kgauthreaux 

- Sorry if it wasn't not clear about SIB vars checks, even if 77 (adopted, unknown) is an allowed value for SIBS, checks like "if SIBS is (>0 and <77) then SIB1YOB must be present" should be modified to **if SIBS (>0 and <=20)**, because, if the participant **has siblings** the max allowed number of siblings is **20** (not 77).
- In Q&V csv there's an extra "missingness" column, please remove that.

2024-10-03 18:15 UTC, kgauthreaux commented
@hewanadun okay I fixed that file and will upload. And thanks for clarifying, but I guess I am just confused because isn't "<77" and "<=20" when the SIBS value will already be checked to be 0-20 or 77 functionally the same thing? the max valid value less than 77 for the SIBS variable is 20.

2024-10-03 20:03 UTC, hewanadun commented
> @hewanadun okay I fixed that file and will upload. And thanks for clarifying, but I guess I am just confused because isn't "<77" and "<=20" when the SIBS value will already be checked to be 0-20 or 77 functionally the same thing? the max valid value less than 77 for the SIBS variable is 20.

Although the interpretation is the same when it's <70, it complicates how we have to implement the rule. We have to take care of the values 21-76 which are not allowed values for SIBS but allowed in the way the rule is written. For the error report also, I think it's more clear to say <=20.

2024-10-04 01:20 UTC, kgauthreaux commented
@hewanadun oh okay, I didn't realize you had to account for everything in between. I updated the files!

2024-10-10 22:09 UTC, echeng06 requested changes
Errors MC
* Looks like a combined version of the MC/plausibility checks was uploaded, please update these to just being the MC checks
     * There are also a lot of extra columns leftover, please clean up
* `a3-ivp-c-002`: Please update to use `/` instead of `-` for the date formats
* `a3-ivp-c-014`, etc.:  Birth year checks are still comparing - 20, needs to be updated to - 15 (both in error checks and Q&V csv) to be compatible with A1 (unless this was resolved to be differently, just basing this off of the above)
* For all KID*, everywhere it says `>X and < 15` should be `>X and <= 15`, similar to SIB*
* All the SIBXDAGE and KIDXDAGE variables need to be SIBXAGD and KIDXAGD instead to match the Q&V csv + REDCap forms
* Everywhere that says `KIDYOB must be a year between 1860 and ...`

2024-10-23 01:06 UTC, kgauthreaux commented
@echeng06 Thanks, Emily. Apologies that I forgot to upload the MC and P check separately. I can do that, although I do not see any extra columns in these files?

One question before I upload - "Everywhere that says KIDYOB must be a year between 1860 and ... needs the numerical variable instead" what does this comment mean? Do you mean that it should be listed as a numerical variable and not an integer in the questions_and_vars file?

2024-10-23 01:41 UTC, echeng06 commented
@kgauthreaux hm might be the editor you're using? If you look at the raw files on github you can see a bunch of commas (`,,,`) which basically means a bunch of empty cells. Not a big deal though, we can clean up later.

Sorry for my bad wording - for that one I mean it should say "KID**1**YOB must be a year between 1860 and...", e.g. should be "KID1YOB" instead of "KIDYOB". And it'll need to be that for all the variables, KID1YOB, KID2YOB, KID3YOB, and so on.

2024-10-23 19:36 UTC, kgauthreaux commented
@echeng06 ah okay, I do use excel but at least to me they are just completely blank and I am not sure how to prevent those commas. Sorry! And thanks for clarifying, not sure how the numbers escaped that column but I updated. Will upload now!

2024-10-23 20:14 UTC, echeng06 approved these changes

2024-10-24 19:08 UTC, hewanadun approved these changes

2024-10-25 02:04 UTC, merged