Add files via upload
naccdata/uniform-data-set pull request #189
Opened 2024-08-23 23:44 UTC by kgauthreaux

Adding header variable error checks to A2

2024-08-28 19:42 UTC, hewanadun requested changes
@kgauthreaux 

- For optional forms such as this one, if MODE is set to "Not completed", is it OK only to validate the header variables? Or do we need to make sure rest of the form is not filled? If we need to validate that, please add another error check under MODE variable (something like _If MODExx = 3, form should not have data filled..._)

- In this file changes are not tracked correctly from the previous version, previous content is shown as deleted and everything is shown as newly added. So I cannot figure out whether there were any changes to previous checks. I assumed only thing changed was the addition of header variables, let me know if there were any other changes.

2024-08-28 19:42 UTC, hewanadun commented on forms/uds/a2/form_a2_ivp_error_checks_mc.csv
> +a2-ivp-m-033,033,Error,a2,I,RMREASA2,Missingness,RMREASA2 conditionally blank,"If MODEA2 = 1, RMREASA2 must be blank",If Q0d. MODEA2 (A2 in person or remote) = 1 (In-person) then Q0d1. RMREASA2 (Reas
Shouldn't this check be "If MODEA2 = 1 or 3" ?

2024-08-28 19:42 UTC, hewanadun commented on forms/uds/a2/form_a2_ivp_error_checks_mc.csv
> +a2-ivp-m-036,036,Error,a2,I,RMMODEA2,Missingness,RMMODEA2 conditionally blank,"If MODEA2 = 1, RMMODEA2 must be blank",If Q0d. MODEA2 (A2 in person or remote) = 1 (In-person) then Q0d1a. RMMODEA2 (Mod
Similar as above, this check should be "If MODEA2 = 1 or 3" ?

2024-08-28 19:42 UTC, hewanadun commented on forms/uds/a2/form_a2_ivp_error_checks_mc.csv
> +a2-ivp-m-038,038,Error,a2,I,A2NOT,Missingness,A2NOT conditionally present,A2NOT cannot be blank,"If Q0d. MODEA2 (A2 in person, remote or not completed) = 3 (not completed) then Q0d2. A2NOT (If form w
Don't we also need to check whether A2NOT is blank when MODEA2 != 3? (similar to checks for other variables)

2024-10-04 17:43 UTC, echeng06 commented
@kgauthreaux Also want to add Q&V csv should update `FRMDATEA2` and `LANGA2` should have their missingness column set to "Always" to reflect the rule requirements

2024-10-23 20:58 UTC, echeng06 requested changes
There are two MC CSVs, I think `a2_ivp_error_checks_mc.csv` is the correct one but please rename it to `form_a2_ivp_error_checks_mc.csv` and delete the old one. Also
* `a2-ivp-m-038`: Needs to be if MODEA2 is 0, not 3
* `a2-ivp-m-040`: Needs to be if MODEA2 is 0, not 3

2024-10-29 15:01 UTC, hewanadun approved these changes

2024-10-29 23:57 UTC, merged