Upload E3F var list and m/c
naccdata/uniform-data-set pull request #211
Opened 2024-10-21 21:24 UTC by jculhane

2024-10-22 00:44 UTC, echeng06 requested changes
* `e3f-ftldivp-m-170` is missing `FTDCBFOA` in `comp_vars`

Looks good otherwise!

2024-10-23 16:25 UTC, echeng06 approved these changes

2024-10-23 23:15 UTC, merged

2024-11-04 22:49 UTC, hewanadun commented
@jculhane 
For the string variables that say "Any text or numbers, but cannot include single quotes (’), double quotes (“), ampersands (&) or percentage signs (%)" in Q&V csv (e.g. FTDMRIOS, FTDFDGOS, etc.), do we need to specifically check if this condition satisfied? If so, please add a conformity check for each for those variables.

2024-11-07 08:25 UTC, jculhane commented
No, we don't - the module Q&Vs are pulled directly from the current (v3) DEDs, and these were requirements in the current SAS system.