Upload A5D2 I4 plausibility
naccdata/uniform-data-set pull request #215
Opened 2024-10-23 23:08 UTC by jculhane

2024-10-25 00:43 UTC, echeng06 requested changes
* `a5d2-ivp-p-1001`: Should be BIRTHSEX=2 not 1 for several columns
* `a5d2-ivp-p-1003`: Typos, should be ALCDRINKS not ALDRINKS
* `a5d2-ivp-p-1007`: Should be under RBD, and on the IVP one we also swapped the order, so we should probably do the same here for consistency (and will be consistent with the other rules as well)
* `a5d2-ivp-p-1020`: Typos, should be OTHANXD not OTHAND
* Error codes need to say `i4vp` not `ivp` 
* Do PDOTHR and CBTIA also need a comparison between UDSv3 and v4?
* `a5d2-i4vp-p-1036` and `a5d2-i4vp-p-1038` are the same, was the latter meant to be CBTIA?

2024-10-26 06:10 UTC, jculhane commented
Apologies for somehow starting with an old version of IVP for these. Fixed!

2024-10-29 16:31 UTC, echeng06 approved these changes

2024-10-29 20:50 UTC, merged

2024-11-15 20:42 UTC, hewanadun commented
@jculhane  As per Teams discussion, please update any equality checks against UDSv3. See section "Exclude Unknown or N/A codes when comparing with a previous visit" in https://github.com/naccdata/uniform-data-set/issues/210#issue-2554408480