Upload C6F missingness & conformity
naccdata/uniform-data-set pull request #221
Opened 2024-10-26 22:34 UTC by kgauthreaux

2024-10-30 00:07 UTC, echeng06 requested changes
* LANGAC6F is misspelled in Q&V CSV, should be LANGC6F
* `c6f-ftldivp-m-007` and `c6f-ftldivp-m-008`: `short_desc` is wrong, please fix

2024-10-31 22:24 UTC, echeng06 approved these changes

2024-11-04 23:24 UTC, hewanadun approved these changes

2024-11-04 23:28 UTC, kgauthreaux commented
@echeng06 @hewanadun once Chandima has approved after Emily, I can merge the pull request, correct?

2024-11-04 23:52 UTC, hewanadun commented
> @echeng06 @hewanadun once Chandima has approved after Emily, I can merge the pull request, correct?

Yes, please merge.

2024-11-04 23:55 UTC, merged