Upload C6F plausibility
naccdata/uniform-data-set pull request #222
Opened 2024-10-26 22:36 UTC by kgauthreaux

2024-10-29 23:54 UTC, echeng06 requested changes
Please update the wording of short_desc to follow a more explicit If/Then convention and be more specific about being/not being 88 and blank, e.g.

- If any of (...VARS...) are blank then PARENTVAR must be 88
- If all of (...VARS...) are not blank then PARENTVAR cannot be 88

Other errors:
* FTDMSCR is misspelled, should be FTDSMSCR

2024-11-05 15:20 UTC, hewanadun approved these changes
Looks good!

2024-11-21 22:52 UTC, hewanadun commented
@echeng06 Please check and approve this PR.

2024-11-21 23:26 UTC, echeng06 approved these changes

2024-11-22 20:25 UTC, merged