Upload B1L missingness & conformity
naccdata/uniform-data-set pull request #228
Opened 2024-10-27 21:39 UTC by kgauthreaux

2024-11-01 21:22 UTC, echeng06 requested changes
Q&V CSV:
* Please change all instances of data type of "Num" to "Integer"
* `LBSSCLOT` type should be a string, unless it really can only be a character (if so, we also need to update some code to support char validation)

Errors CSV:
* `short_desc` has a typo of "a an integer..." in a bunch of rules, please clean up

2024-11-05 18:59 UTC, echeng06 approved these changes

2024-11-05 20:53 UTC, hewanadun submitted a review, later dismissed

2024-11-05 21:05 UTC, echeng06 requested changes
* `b1l-lbdivp-c-002` should be under FRMDATEB1L not INITIALSB1L

2024-11-07 23:47 UTC, hewanadun approved these changes

2024-11-12 19:33 UTC, echeng06 approved these changes

2024-11-13 23:50 UTC, merged