LBD - Upload B3L missingness & conformity
naccdata/uniform-data-set pull request #240
Opened 2024-10-31 00:50 UTC by kgauthreaux

2024-11-01 21:41 UTC, echeng06 requested changes
Q&V CSV:
* `data_type` is missing for most of the variables, please update (Integer and String)

Errors CSV:
* The first two rules are under XX, please update to b3l and move rules to bottom (making them error codes 113 and 114)
* `short_desc` has the "a an integer" typo for a lot of rules, please clean up
* `b3l-lbdivp-m-008`: Should be 0-4, not 1-4

2024-11-05 21:03 UTC, hewanadun commented
@kgauthreaux No LANGXX field in LBD form headers, is that correct?

2024-11-12 17:05 UTC, echeng06 approved these changes

2024-11-12 17:22 UTC, hewanadun approved these changes

2024-11-12 18:29 UTC, merged