Upload revised B4 IVP and I4 p (PR#216 comments)
naccdata/uniform-data-set pull request #252
Opened 2024-11-05 04:09 UTC by jculhane

https://github.com/naccdata/uniform-data-set/pull/216

2024-11-05 18:36 UTC, echeng06 requested changes
For both:
* `1004` and `1005`: Please update `test_name` as well

2024-11-06 16:57 UTC, echeng06 approved these changes

2024-11-06 17:41 UTC, hewanadun approved these changes

2024-11-06 23:45 UTC, merged

2024-11-15 20:56 UTC, hewanadun commented
@jculhane As per Teams discussion, please double check `cdrglob` check against UDSv3. See section "Exclude Unknown or N/A codes when comparing with a previous visit" in https://github.com/naccdata/uniform-data-set/issues/210#issue-2554408480