LBD - Upload v3 B2L var list and m/c
naccdata/uniform-data-set pull request #254
Opened 2024-11-05 07:06 UTC by jculhane

2024-11-05 23:34 UTC, echeng06 requested changes
Q&V CSV:
* Please update `data_type` "Num" to "Integer"
* `conformity` should also probably be updated to specify that they're integers

Errors CSV:
* `short_desc` has "a an" typo for a lot rules, please update
* ~~`do_in_redcap` and `in_previous_versions` not filled out~~

2024-11-06 23:58 UTC, echeng06 requested changes
Looks like the `conformity` column got auto incremented, they should all be 9. Otherwise changes looks good!

2024-11-07 17:10 UTC, echeng06 approved these changes

2024-11-07 17:28 UTC, hewanadun approved these changes

2024-11-07 17:39 UTC, hewanadun commented
@jculhane Just noticed that `error_no` column is missing leading zeros. Please make it consistent with other forms.

2024-11-07 18:21 UTC, merged