LBD - Upload v3 D1L var list and m/c
naccdata/uniform-data-set pull request #259
Opened 2024-11-05 18:09 UTC by jculhane

2024-11-06 00:38 UTC, echeng06 requested changes
Both:
* Questions 4f-4l from the PDF is missing here

Q&V
* Some typos of "Inetgers" in `conformity`
* Last two variables are missing `data_type`
* `packet` should be IL, not I

Errors:
* `short_desc` "a an" typo
* ~~`do_in_redcap` and `in_prev_versions` missing for most rows~~

2024-11-07 19:18 UTC, echeng06 submitted a review, later dismissed

2024-11-08 00:18 UTC, hewanadun reviewed
Fix `error_no` column, rest looks good.

2024-11-08 00:40 UTC, hewanadun approved these changes

2024-11-08 06:35 UTC, merged