LBD - Upload v3 B4L plausibility
naccdata/uniform-data-set pull request #265
Opened 2024-11-08 02:24 UTC by kgauthreaux

2024-11-08 04:06 UTC, echeng06 requested changes
* `b4l-lbdivp-p-1002 - 1005`: `short_desc` and `test_logic` should be checking for 0, I think they got auto-incremented

2024-11-08 21:15 UTC, kgauthreaux commented
@echeng06 oops yes looks like it was an auto fill error!

2024-11-08 22:10 UTC, echeng06 approved these changes

2024-11-13 00:09 UTC, kgauthreaux commented
@echeng06 okay uploading with checks for those age of onset variables to be 888 and also some extra checks against the UDSv5 NPI which measures some of the same things

2024-11-13 00:34 UTC, echeng06 approved these changes

2024-11-22 20:29 UTC, merged