FTLD - upload b3f FVP plausibility
naccdata/uniform-data-set pull request #267
Opened 2024-11-08 04:55 UTC by jculhane

2024-11-08 20:18 UTC, echeng06 requested changes
* `b3f-ftldfvp-p-1014`: `test_name` should reference FTDGSEV

2024-11-09 21:59 UTC, hewanadun approved these changes

2024-11-13 17:56 UTC, echeng06 approved these changes

2024-11-14 16:59 UTC, merged

2024-11-15 20:04 UTC, hewanadun commented
@jculhane @echeng06 As per Teams discussion that Form B8 can be left blank, please modify below form B3F checks to have B8 variable checked first
- IVP - b3f-ftldivp-p-1011 => `If GAITABN=8 then FTDGTYP should =8`
- FVP - b3f-ftldfvp-p-1015 => `If GAITABN=8 then FTDGTYP should =8`