LBD - upload e1l
naccdata/uniform-data-set pull request #269
Opened 2024-11-10 04:31 UTC by jculhane

2024-11-13 05:56 UTC, jculhane commented
Correct - FVP plausibility is the same as IVP

2024-11-13 17:30 UTC, echeng06 submitted a review, later dismissed

2024-11-14 17:52 UTC, hewanadun requested changes
In FVP, since the rest of the form can be left blank if `LBGNEWGN = 0`
- In Q&V, update rest of the variables to be `Conditional` and update `conformity` column to allow blank
- In m/c checks, need to add `If LBGNEWGN=1 and ....` to all `cannot be blank` checks
    e.g.  008 =>`If LBGNEWGN=1 and LBGLRRK2 = 1, then LBGLRKIS cannot be blank`
- We need a check to verify that the form is left blank if `LBGNEWGN = 0` 
    (I think vice versa is covered by current checks?)

If `LBGNEWGN=1`, do they have to pick a value for each question or can they update only some of the questions? From the error checks it seems they have to fill all, just checking whether that is the correct assumption.

2024-11-17 05:57 UTC, jculhane commented
Yes, if LBGNEWGN=1, they have to pick a value for each question

2024-11-21 17:46 UTC, hewanadun approved these changes

2024-11-21 17:56 UTC, merged