LBD - upload c1l v3 ivp plausibility
naccdata/uniform-data-set pull request #270
Opened 2024-11-10 04:40 UTC by jculhane

2024-11-12 20:34 UTC, echeng06 approved these changes

2024-11-15 00:13 UTC, hewanadun requested changes
Can we modify 
- 1002 to `If LBNPFACE is in (0-7) and LBNPNOIS is in (0-13), ...`
- 1003 to `If LBNPNOIS is in (0-13) and LBNPPARD is in (0-13), ...`

2024-11-15 06:44 UTC, jculhane commented
> Can we modify
> 
> * 1002 to `If LBNPFACE is in (0-7) and LBNPNOIS is in (0-13), ...`
> * 1003 to `If LBNPNOIS is in (0-13) and LBNPPARD is in (0-13), ...`

@hewanadun These edits aren't strictly necessary (LBNPNOIS will always be in (0-13) if LBNPFACE is in (0-7), and LBNPPARD will always be in (0-13) if LBNPNOIS is in (0-13). Happy to add if it helps you/Emily transfer them into code though - let me know.

2024-11-15 14:01 UTC, hewanadun commented
@jculhane We need to add it in the rule definition to prevent the validator code crashing if the form is not filled correctly (i.e. if LBNPNOIS left blank even when LBNPFACE in 0-7). Having it in error checks helps automation, otherwise we have to add that manually to the definition. Thanks!

2024-11-21 22:57 UTC, hewanadun approved these changes

2024-11-22 05:29 UTC, merged