LBD - Upload v3.1 B1L IVP and FVP var list and m/c
naccdata/uniform-data-set pull request #275
Opened 2024-11-11 06:09 UTC by jculhane

2024-11-12 19:44 UTC, echeng06 requested changes
Q&V: 
* Several variables missing 777 in `conformity`

2024-11-13 17:31 UTC, echeng06 requested changes
LBSAGERM is still missing 777

2024-11-13 17:42 UTC, echeng06 submitted a review, later dismissed

2024-11-14 14:49 UTC, hewanadun requested changes
Need to differentiate b/w v3 and v3.1 error codes (https://github.com/naccdata/uniform-data-set/pull/276#pullrequestreview-2436233722). Update 3.1 error codes to following format 
For IVP - `<form>-lbd3.1ivp-<type>-<number>`
For FVP - `<form>-lbd3.1fvp-<type>-<number>`

2024-11-15 22:34 UTC, hewanadun approved these changes

2024-11-16 04:14 UTC, merged