LBD - Upload v3.1 B2L IVP m/c
naccdata/uniform-data-set pull request #276
Opened 2024-11-11 06:19 UTC by jculhane

2024-11-13 17:31 UTC, echeng06 submitted a review, later dismissed

2024-11-14 14:02 UTC, hewanadun submitted a review, later dismissed

2024-11-14 14:24 UTC, hewanadun requested changes
@jculhane @echeng06 
For the forms that the error checks are different b/w LBD v3 and v3.1 we can't use the same error codes for both versions. Need some way to differentiate.
For v3.1, can we use the format `<form>-lbd3.1ivp-<type>-<number>`?

2024-11-15 22:31 UTC, hewanadun approved these changes

2024-11-16 04:15 UTC, merged