LBD - Upload v3 B4L FVP plausibility
naccdata/uniform-data-set pull request #281
Opened 2024-11-13 08:11 UTC by jculhane

2024-11-14 21:29 UTC, echeng06 requested changes
* `b4l-lbdfvp-p-1018` I think is supposed to be referencing LBDAGE, not LBANXAGE

2024-11-15 16:03 UTC, hewanadun commented
- For checks 1018 - 1022, I think we should check equality only if they enter a valid age. 
   For example 1008 => `If LBDAGE in (15 - 110) and LBDAGE[prev_vis] in (15 - 110), LBDAGE should equal LBDAGE[prev_vis]`
- If 777 is entered for a question, do we need to check whether the value is provided in the previous visit?

2024-11-21 00:43 UTC, jculhane commented
Yes, they can keep entering 777. Fixed!

2024-11-27 19:51 UTC, echeng06 approved these changes

2024-11-27 20:21 UTC, hewanadun approved these changes

2024-12-02 04:37 UTC, merged