LBD FVP - Upload v3 B1L missingness & conformity
naccdata/uniform-data-set pull request #282
Opened 2024-11-13 23:54 UTC by kgauthreaux

2024-11-14 00:31 UTC, echeng06 requested changes
This is in the IVP Q&V sorry I only noticed after comparing the two, we can fix it in this branch:
* Some of the `question` cells have hyphens in odd places
    * LBSSALIV: "drib-ble"
    * LBSDBVIS: "expe-rience"

FVP rules themselves look good to me otherewise!

2024-11-15 00:23 UTC, kgauthreaux commented
@echeng06 hmm very odd, it must have been something that happened when it got converted to CSV from the SharePoint excel file since it looks fine on there. Hopefully it looks fine now!

2024-11-15 00:27 UTC, echeng06 commented
@kgauthreaux LBSDBVIS still has it with "expe-rience" but the other one looks good

2024-11-15 00:44 UTC, echeng06 approved these changes

2024-11-15 03:27 UTC, hewanadun approved these changes

2024-11-15 23:34 UTC, merged