FTLD FVP - Upload B9F plausibility
naccdata/uniform-data-set pull request #290
Opened 2024-11-15 23:12 UTC by kgauthreaux

2024-11-20 06:31 UTC, jculhane commented
@kgauthreaux I made some updates to the IVP plausibility based on [PR#266](https://github.com/naccdata/uniform-data-set/pull/266#pullrequestreview-2439633917). I copied these over to the FVP Excel sheet but didn't upload to Github.

2024-11-27 06:14 UTC, echeng06 requested changes
* 1006 - 1010: PPASYNT is the wrong value in `short_desc`

2024-11-27 21:49 UTC, echeng06 approved these changes

2024-12-03 15:58 UTC, hewanadun approved these changes

2024-12-03 20:32 UTC, merged