UDS - Upload A5D2 var list and m/c
naccdata/uniform-data-set pull request #301
Opened 2024-11-18 06:03 UTC by jculhane

Couple of small changes from UDS pilot feedback

2024-11-19 00:46 UTC, echeng06 requested changes
* `a5d2-ivp-m-094`: Test logic incorrect, should be "IF ANGIOCP ne 1 and CAROTIDAGE is not blank"

Also just want to confirm 093 and 094 were the only two rules that were updated - it's all I see but the diff is large so I might have missed it.

2024-11-19 22:14 UTC, jculhane commented
Fixed. Correct - 093 and 094 were the only rules that were updated.

2024-11-19 22:28 UTC, echeng06 approved these changes

2024-11-21 23:00 UTC, hewanadun approved these changes

2024-11-22 05:28 UTC, merged