UDS - Upload D1b I4 plausibility
naccdata/uniform-data-set pull request #309
Opened 2024-11-22 20:15 UTC by jculhane

2024-11-22 20:27 UTC, echeng06 requested changes
* `1002/1003` has the same mixup as IVP
* `1005 - 1008`: Please update `short_desc` to use VAR[UDSv3] notation

2024-11-22 21:07 UTC, jculhane commented
Sorry about that! Fixed.

2024-11-22 21:10 UTC, echeng06 approved these changes

2024-11-26 14:56 UTC, hewanadun approved these changes

2024-11-26 17:14 UTC, merged